# Generated by Django 2.2.19 on 2021-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='testfield',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
